services:
- type: web
name: school-project
env: python
buildCommand: |
pip install --upgrade pip
pip install --no-binary :all: -r requirements.txt
python manage.py collectstatic --noinput
startCommand: gunicorn school_project.wsgi:application
