# Generated by Django 4.2.26 on 2025-11-27 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('grade_level', models.CharField(default='Grade 1', max_length=50, verbose_name='grade level')),
                ('section', models.CharField(blank=True, max_length=10, verbose_name='section')),
                ('room_number', models.CharField(blank=True, max_length=10, verbose_name='room number')),
                ('capacity', models.IntegerField(default=30, verbose_name='capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Class Room',
                'verbose_name_plural': 'Class Rooms',
                'ordering': ['grade_level', 'section'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('books', 'Books'), ('sports', 'Sports Equipment'), ('lab', 'Lab Equipment'), ('office', 'Office Supplies'), ('other', 'Other')], default='other', max_length=20, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='supplier')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase price')),
                ('condition', models.CharField(blank=True, max_length=50, verbose_name='condition')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=50, verbose_name='المستوى')),
                ('day', models.CharField(choices=[('sunday', 'الأحد'), ('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس')], max_length=10, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='المادة')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='الأستاذ')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='القاعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'حصة',
                'verbose_name_plural': 'جدول الحصص',
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trust Academy School', max_length=200, verbose_name='school name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/', verbose_name='logo')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name='academic year')),
                ('currency', models.CharField(default='DZD', max_length=10, verbose_name='currency')),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='staff ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('position', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Administrator'), ('principal', 'Principal'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('librarian', 'Librarian')], default='teacher', max_length=20, verbose_name='position')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='hire date')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['position', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='student ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name_arabic', models.CharField(blank=True, max_length=100, verbose_name='first name (Arabic)')),
                ('last_name_arabic', models.CharField(blank=True, max_length=100, verbose_name='last name (Arabic)')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('grade_level', models.CharField(default='Grade 1', max_length=50, verbose_name='grade level')),
                ('parent_name', models.CharField(max_length=200, verbose_name='parent name')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='parent phone')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='parent email')),
                ('parent_address', models.TextField(blank=True, verbose_name='parent address')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='medical conditions')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='enrollment date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='photo')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_management.classroom', verbose_name='class room')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['grade_level', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('grade_level', models.CharField(default='Grade 1', max_length=50, verbose_name='grade level')),
                ('credits', models.IntegerField(default=1, verbose_name='credits')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'position': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.staff', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('level', models.CharField(max_length=50, verbose_name='Level')),
                ('registration_number', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('institution_name', models.CharField(default='Trust Academy', max_length=200, verbose_name='Institution Name')),
                ('license_number', models.CharField(default='2491/21', max_length=50, verbose_name='License Number')),
                ('director_name', models.CharField(default='مديرة Trust Academy', max_length=100, verbose_name='Director Name')),
                ('issue_city', models.CharField(default='بومرداس', max_length=100, verbose_name='Issue City')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Certificate Number')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Is Issued')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'verbose_name_plural': 'Student Certificates',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('transport', 'Transport Fee'), ('lunch', 'Lunch Fee'), ('uniform', 'Uniform Fee'), ('books', 'Books Fee'), ('other', 'Other')], default='tuition', max_length=20, verbose_name='payment type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='receipt number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.staff', verbose_name='created by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school_management.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-due_date', 'student'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.staff', verbose_name='teacher'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1, verbose_name='semester')),
                ('year', models.IntegerField(default=2024, verbose_name='year')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='score')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.staff', verbose_name='graded by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school_management.student', verbose_name='student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-year', '-semester', 'student'],
                'unique_together': {('student', 'subject', 'semester', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade_level', 'section')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recorded at')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.staff', verbose_name='recorded by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school_management.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['-date', 'student'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
