# Generated by Django 4.2.26 on 2025-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['grade_level', 'day', 'start_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], max_length=10, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='grade_level',
            field=models.CharField(max_length=50, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teacher'),
        ),
    ]
