# Generated by Django 4.2.26 on 2025-11-30 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_alter_schedule_options_alter_schedule_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], max_length=2, verbose_name='month')),
                ('year', models.IntegerField(default=2025, verbose_name='year')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base salary')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='overtime hours')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='overtime rate')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='bonus')),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='other earnings')),
                ('cnaps', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CNAPS')),
                ('cacobatph', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CACOBATPH')),
                ('casnos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CASNOS')),
                ('irg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IRG')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='advance')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='other deductions')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='gross salary')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='net salary')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.staff', verbose_name='staff member')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-year', '-month', 'staff'],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
    ]
