# Generated by Django 4.2.26 on 2025-11-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank account number'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_rib',
            field=models.CharField(blank=True, help_text="Relevé d'Identité Bancaire", max_length=50, verbose_name='bank RIB'),
        ),
        migrations.AddField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='blood group'),
        ),
        migrations.AddField(
            model_name='staff',
            name='cin_number',
            field=models.CharField(blank=True, help_text="Numéro de carte d'identité nationale", max_length=20, verbose_name='CIN number'),
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, default='Boumerdes', max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contract_type',
            field=models.CharField(blank=True, default='CDI', max_length=50, verbose_name='contract type'),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='emergency phone'),
        ),
        migrations.AddField(
            model_name='staff',
            name='family_situation',
            field=models.CharField(choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], default='single', max_length=20, verbose_name='family situation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='first name (Arabic)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='last name (Arabic)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='Algérienne', max_length=50, verbose_name='nationality'),
        ),
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='staff',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0, verbose_name='number of children'),
        ),
        migrations.AddField(
            model_name='staff',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='passport number'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='staff',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='staff',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, verbose_name='qualification'),
        ),
        migrations.AddField(
            model_name='staff',
            name='retirement_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='retirement number'),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='salary grade'),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_scale',
            field=models.CharField(blank=True, max_length=10, verbose_name='salary scale'),
        ),
        migrations.AddField(
            model_name='staff',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='Numéro de sécurité sociale (15 chiffres)', max_length=20, verbose_name='social security number'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='specialization'),
        ),
        migrations.AddField(
            model_name='staff',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='years of experience'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Administrator'), ('principal', 'Principal'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('librarian', 'Librarian'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('other', 'Other')], default='teacher', max_length=20, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salaire de base en DZD', max_digits=10, verbose_name='base salary'),
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
