# Generated by Django 4.2.26 on 2025-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_staff_bank_account_number_staff_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bank_rib',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='retirement_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary_grade',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary_scale',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='staff',
            name='family_situation',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], default='single', max_length=20, verbose_name='family situation'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, default='Algérienne', max_length=50, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='Numéro de sécurité sociale', max_length=20, verbose_name='social security number'),
        ),
    ]
