# Generated by Django 4.2.26 on 2025-11-30 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_alter_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], max_length=2, verbose_name='month')),
                ('year', models.IntegerField(default=2025, verbose_name='year')),
                ('echelon', models.CharField(choices=[('1', 'Échelon 1'), ('2', 'Échelon 2'), ('3', 'Échelon 3'), ('4', 'Échelon 4'), ('5', 'Échelon 5'), ('6', 'Échelon 6'), ('7', 'Échelon 7'), ('8', 'Échelon 8'), ('9', 'Échelon 9'), ('10', 'Échelon 10'), ('11', 'Échelon 11'), ('12', 'Échelon 12')], default='1', max_length=2, verbose_name='échelon')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salaire de base')),
                ('indemnite_residence', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='indemnité de résidence')),
                ('indemnite_zone', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='indemnité de zone')),
                ('indemnite_pedagogique', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='indemnité pédagogique (IP)')),
                ('indemnite_documentation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='indemnité de documentation')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='heures supplémentaires')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux heures supp.')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant heures supp.')),
                ('prime_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="prime d'ancienneté")),
                ('autres_indemnites', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='autres indemnités')),
                ('autres_primes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='autres primes')),
                ('cotisation_cnas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cotisation CNAS')),
                ('cotisation_retraite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cotisation retraite (CNR)')),
                ('irg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='impôt sur le revenu (IRG)')),
                ('mutuelle_mgen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='mutuelle (MGEN)')),
                ('avance_salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='avance sur salaire')),
                ('cotisation_syndicale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cotisation syndicale')),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='autres retenues')),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total brut')),
                ('total_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total des retenues')),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='net à payer')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank', 'Virement bancaire'), ('check', 'Chèque')], default='bank', max_length=20, verbose_name='payment method')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.staff', verbose_name='staff member')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-year', '-month', 'staff__last_name'],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
    ]
