# Generated by Django 4.2.26 on 2025-12-01 12:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_payroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-month', 'staff__last_name'], 'verbose_name': 'Fiche de Paie', 'verbose_name_plural': 'Fiches de Paie'},
        ),
        migrations.AlterField(
            model_name='payroll',
            name='autres_indemnites',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='autres indemnités'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='autres_primes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='autres primes'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='autres_retenues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='autres retenues'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='avance_salaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='avance sur salaire'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='salaire de base'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cotisation_cnas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cotisation CNAS (9%)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cotisation_retraite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cotisation retraite CNR (7.5%)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cotisation_syndicale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cotisation syndicale'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='indemnite_documentation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='indemnité de documentation'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='indemnite_pedagogique',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='indemnité pédagogique (IP)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='indemnite_residence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='indemnité de résidence'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='indemnite_zone',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='indemnité de zone'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='irg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='impôt sur le revenu (IRG)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='mutuelle_mgen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='mutuelle MGEN (1.5%)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_a_payer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='net à payer'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='montant heures supp.'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='taux heures supp.'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank', 'Virement bancaire'), ('check', 'Chèque'), ('transfer', 'Virement'), ('other', 'Autre')], default='bank', max_length=20, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='prime_anciennete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="prime d'ancienneté"),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='school_management.staff', verbose_name='staff member'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_brut',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='total brut'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_retenues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='total des retenues'),
        ),
    ]
