# Generated by Django 4.2.26 on 2025-12-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0010_clear_subject_teachers'),
    ]

    operations = [
    ]
