"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 4.2.26.
"""

import os
import socket
from pathlib import Path
import dj_database_url

# Database configuration
if 'RENDER' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-change-this-in-production-to-a-random-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Auto-detect current IP address
def get_current_ip():
    """Get the current local IP address automatically"""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        print(f"🔍 Auto-detected IP: {ip}")  # For debugging
        return ip
    except Exception as e:
        print(f"⚠️ Could not auto-detect IP: {e}")
        return None

# Get current IP
current_ip = get_current_ip()

# ALLOWED HOSTS with auto-detected IP
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '0.0.0.0',
    '10.49.162.*',     # Your network range
]

# Add auto-detected IP if available
if current_ip:
    ALLOWED_HOSTS.append(current_ip)
    # Also add the IP with wildcard for network range
    network_range = '.'.join(current_ip.split('.')[:3]) + '.*'
    if network_range not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(network_range)

print(f"✅ ALLOWED_HOSTS: {ALLOWED_HOSTS}")  # For debugging

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'school_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Keep for language detection
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'school_management', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For language support
                # Custom context processors
                'school_management.context_processors.school_info',
                'school_management.context_processors.language_context',  # Added for language switcher
            ],
        },
    },
]

WSGI_APPLICATION = 'school_project.wsgi.application'

# Database
# Use SQLite for easier local development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== INTERNATIONALIZATION ====================
# ✅ MULTI-LANGUAGE CONFIGURATION (Python-only approach)

LANGUAGE_CODE = 'en'  # Default language

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'French'),
    ('ar', 'Arabic'),
]

# ✅ UNCOMMENTED - Django needs this to find translation files!
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Timezone settings for Algeria
TIME_ZONE = 'Africa/Algiers'

USE_I18N = True  # Internationalization - KEEP THIS for basic language support
USE_L10N = True  # Localization
USE_TZ = True

# ==================== END INTERNATIONALIZATION ====================

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Static files directories
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'school_management', 'static'),
]

# Static root for collectstatic command
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (uploaded files like logos, student photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Create basic media directories on startup
media_dirs = ['students/photos', 'staff/photos', 'documents', 'certificates']
for dir_path in media_dirs:
    os.makedirs(os.path.join(MEDIA_ROOT, dir_path), exist_ok=True)

print("✅ Media directories created")

# Create media directories if they don't exist
os.makedirs(os.path.join(BASE_DIR, 'media', 'students'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media', 'staff'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media', 'documents'), exist_ok=True)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Email Configuration (for password reset, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Prints emails to console

# WhatsApp Configuration
WHATSAPP_COUNTRY_CODE = '213'  # Algeria

# School Configuration
SCHOOL_NAME = "Trust Academy"
SCHOOL_ADDRESS = "Boumerdes, Algeria"
SCHOOL_PHONE = "+213 540 804 219"
SCHOOL_EMAIL = "info@trustacademy.edu.dz"
SCHOOL_WEBSITE = ""

# Auto-configure CSRF_TRUSTED_ORIGINS with current IP
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8080',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8080',
]

# Add current IP to CSRF trusted origins
if current_ip:
    CSRF_TRUSTED_ORIGINS.extend([
        f'http://{current_ip}:8000',
        f'http://{current_ip}:8080',
    ])

print(f"✅ CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")  # For debugging

CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'   # ← prevents the ugly "Request aborted" page

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'school_management': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Custom settings
MAX_STUDENTS_PER_CLASS = 30
DEFAULT_CURRENCY = 'DZD'
ACADEMIC_YEAR = '2025-2026'  # Updated academic year

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Cache configuration (simple in-memory cache for development)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Auto-create necessary directories on startup
def create_necessary_directories():
    directories = [
        STATIC_ROOT,
        MEDIA_ROOT,
        os.path.join(BASE_DIR, 'logs'),
        os.path.join(MEDIA_ROOT, 'students'),
        os.path.join(MEDIA_ROOT, 'staff'),
        os.path.join(MEDIA_ROOT, 'documents'),
        os.path.join(MEDIA_ROOT, 'certificates'),
        os.path.join(BASE_DIR, 'locale'),  # ✅ Added locale directory
    ]
    
    for directory in directories:
        os.makedirs(directory, exist_ok=True)

# Create directories when settings are loaded
create_necessary_directories()

# Disable related widget for User model
DJANGO_ADMIN_RELATED_FIELD_WIDGET_OVERRIDES = {
    'school_management.Subject': {
        'teacher': {'widget': 'django.forms.Select'},
    }
}

# Print language settings for debugging
print(f"✅ LANGUAGE CONFIGURATION:")
print(f"   - LANGUAGE_CODE: {LANGUAGE_CODE}")
print(f"   - LANGUAGES: {[lang[0] for lang in LANGUAGES]}")
print(f"   - USE_I18N: {USE_I18N}")
print(f"   - TIME_ZONE: {TIME_ZONE}")
print(f"   - LOCALE_PATHS: {LOCALE_PATHS}")
print(f"   - ✅ Gettext dependency removed - Translations will work!")

# ==================== RENDER CONFIGURATION ====================
if 'RENDER' in os.environ:
    # Render PostgreSQL configuration (override the earlier one)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
    
    # Turn off DEBUG mode in production
    DEBUG = False
    
    # Add Render hostname to ALLOWED_HOSTS
    RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
    # Add HTTPS to CSRF_TRUSTED_ORIGINS for Render
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
    
    # Add security settings for production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Use WhiteNoise for static files
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    
    print(f"✅ Render production mode activated")
    print(f"✅ ALLOWED_HOSTS: {ALLOWED_HOSTS}")
else:
    # Local development settings
    DEBUG = True
    print("✅ Local development mode")
